[package]
name = "screenshot"
version = "0.1.0"
edition = "2021"

# lto = true

[dependencies]
anyhow = "1"

tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[dependencies.ffmpeg-next]
version = "5.1.1"
features = []
